AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topic with Email Subscription

Parameters:
  Prefix:
    Type: String
    Default: myapp

  Email:
    Type: String

Resources:

  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Prefix}-dev-alerts-topic"

  EmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref AlertsTopic
      Protocol: email
      Endpoint: !Ref Email

  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref AlertsTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowS3Publish
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sns:Publish
            Resource: !Ref AlertsTopic
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::${Prefix}-dev-${AWS::AccountId}"